spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huangjhLyl/conf-recp.git
          password: 486213@hjh
          username: huangjhLyl
          basedir: F:\ideaWork\managementSys\baseDir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
