spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huangjhLyl/SpringCloud_Sell.git
          password: 486213@hjh
          username: huangjhLyl
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
