spring:
  application:
    name: adminRole
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manage?serverTimezone=GMT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl